### ISSUE TITLE
Problem with ever2simple: from html2text import _html2text

### ISSUE THREAD

**Issue by DorjeTrollo** [claytron/ever2simple#2]
I followed instructions, installed into a virtualenv, etc.  and got error
==== Error 1
from html2text import _html2text
ImportError: cannot import name _html2text
==== Error 1
so i changed the line to:  import html2text
and changed line 85 to:   html2plain = html2text.html2text(None, "")
and got a different error
==== Error 2
  File "/lib/python2.7/site-packages/ever2simple/html2text.py", line 234, in feed
    data = data.replace("</' + 'script>", "</ignore>")
AttributeError: 'NoneType' object has no attribute 'replace'
==== Error 2
So it doesn't like the None in line 85 of your convertor?
I changed it to str: html2plain = html2text.html2text(str, "") 
and got...
==== Error 3
File "lib/python2.7/site-packages/ever2simple/html2text.py", line 234, in feed
    data = data.replace("</' + 'script>", "</ignore>")
TypeError: replace() takes at least 2 arguments (1 given)
==== Error 3
of course that doesn't even begin to address the fact that what I really need is a CSV...
but any help or suggestions would be appreciated. Thanks.

**Comment by csu** [comment]
I'm having this same problem.

```
  File "/Users/christophersu/Desktop/ever2simple/env/lib/python2.7/site-packages/ever2simple-1.0a3-py2.7.egg/ever2simple/converter.py", line 7, in <module>
    from html2text import _html2text
ImportError: cannot import name _html2text
```

**Comment by wb4r** [comment]
same same
